### ISSUE TITLE
Create new database

### ISSUE THREAD

**Issue by hjansen** [pitluga/keepassx#11]
Hi,

is it possible to create a new database from scratch ? Could you give an examnple?

Thx and greetings

Holger

**Comment by n-rodriguez** [comment]
https://github.com/pitluga/keepassx/blob/master/spec/keepassx/keepassx_spec.rb#L5

**Comment by n-rodriguez** [comment]
I know the doc is missing here... I'm sorry for that, but the happily the gem is well tested :)

https://github.com/pitluga/keepassx/blob/master/spec/keepassx/database_spec.rb#L495

**Comment by hjansen** [comment]
Thx for the fast reply, but still im confused on how to proceed.

I got this so far:

`
require 'keepassx'
database = Keepassx::Database.new("database.kdb")
`

How do i add a new entry to the database that i just created ? I looked at the source but it it just not obvious on howto create a new entry, I think i even need to create a group before i can and an entry?

**Comment by n-rodriguez** [comment]
>  I think i even need to create a group before i can and an entry?

I can't remember but given the specs I would say yes

**Comment by hjansen** [comment]
Stupid question and not related to this, but the database format is still Keepass 1 format, correct ? because i thought KeePassX would be KeePass 2 format.

**Comment by n-rodriguez** [comment]
> but the database format is still Keepass 1 format, correct ?

Correct. See 
* https://gist.github.com/lgg/e6ccc6e212d18dd2ecd8a8c116fb1e45
* https://github.com/pitluga/keepassx/blob/master/lib/keepassx/header.rb#L9

**Comment by hjansen** [comment]
Uff so there i no way to create a kdbx file with this lib, correct ? Do you know of any other way on doing that? I have a RoR appication that stores passwords and i would like to serve a kdbx file via https to KeePass in order to use the passwords at the clients that are managed by the RoR application.

**Comment by n-rodriguez** [comment]
> I have a RoR appication that stores passwords and i would like to serve a kdbx file via https to KeePass in order to use the passwords at the clients that are managed by the RoR application.

déjà vu ^^ already done that before but I did it with this lib.

> Uff so there i no way to create a kdbx file with this lib, correct ?

More precisely there is no way to create a Keepass2 db file with this lib. Only Keepass1 (the extension doesn't matter).

**Comment by n-rodriguez** [comment]
I get what you mean about the extension : 

Keepass1: `.kdb`
Keepass2: `.kdbx`

**Comment by n-rodriguez** [comment]
> Do you know of any other way on doing that?

Unfortunately no :/
