### ISSUE TITLE
Could not install keepassx gem on ruby 2.0.1

### ISSUE THREAD

**Issue by tioteath** [pitluga/keepassx#3]
`fast-aes` gem won't install  on ruby 2.0.1 (nateware/fast-aes#8). Besides, reading its issues I found this one: nateware/fast-aes#4, which claims it's insecure. Maybe there's way to port `keepassx` gem to different security library.

**Comment by n-rodriguez** [comment]
Hi! KeepassX don't use fast-aes any more, closing it.
