### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by n-rodriguez** [pitluga/keepassx#6]
Hi there!

First thank you for this useful gem :)
But I'd like to know if you still maintain this project?
I've got a fork with a bunch of patches ready to be merged :)

Thank you!

**Comment by pitluga** [comment]
Hey no problem! Glad you are finding it useful.

I haven't used or thought about this gem in quite a while. Interested in becoming a committer?

**Comment by n-rodriguez** [comment]
> Interested in becoming a committer?

Sure :)

**Comment by pitluga** [comment]
Yay! You're all set. Open the PR and I'll take a look. Then I'll give you access to rubygems.
