### ISSUE TITLE
New release on rubygems.org

### ISSUE THREAD

**Issue by tuxmea** [pitluga/keepassx#9]
Can we have a new release on rubygems.org?
Latest build on rubygems.org is from 2012.
Latest commit is from 2019.

**Comment by n-rodriguez** [comment]
I don't think it will happen : https://github.com/pitluga/keepassx/issues/8

**Comment by pitluga** [comment]
Hi there. Yeah, I've not done a great job stewarding this gem for the past 5 years or so. Sorry about that. I'm open to adding contributors, would either (or both) of you like to take that on?

**Comment by n-rodriguez** [comment]
>  I'm open to adding contributors, would either (or both) of you like to take that on?

sure!

**Comment by pitluga** [comment]
Is your email on your profile the one I should use for rubygems?

**Comment by n-rodriguez** [comment]
> Is your email on your profile the one I should use for rubygems?

yes

**Comment by pitluga** [comment]
This is done, you should now have rights to push this gem. Thanks for taking this on!

**Comment by n-rodriguez** [comment]
> This is done, you should now have rights to push this gem. Thanks for taking this on!

Thank you!

**Comment by n-rodriguez** [comment]
@tuxmea Done! https://rubygems.org/gems/keepassx :rocket:
